version: "2"

services:
  solaranzeige:
#    build: .
    image: "docker.io/acoby/solaranzeige:latest"
    restart: "unless-stopped"
    depends_on:
      - influxdb
      - grafana
    ports:
      - 1883:1883
      - 8080:80
    volumes:
#      - ./app/var/www:/var/www
      - ./data/log:/var/log
    env_file:
      - .env

  grafana:
    image: "docker.io/grafana/grafana:main"
    restart: "unless-stopped"
    depends_on:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - .env

  influxdb:
    image: "docker.io/influxdb:1.8"
    restart: "unless-stopped"
    volumes:
      - ./data/influx:/var/lib/influxdb
    env_file:
      - .env
