version: "2"

services:
  solaranzeige:
    build: .
#    image: "takealug/solaranzeige:latest"
    restart: "unless-stopped"
    depends_on:
      - influxdb
    ports:
      - 1883:1883
      - 8080:80
    volumes:
      - ./app/var/www:/var/www
    tmpfs:
      - /var/log
      - /tmp
    environment:
      - TIMEZONE=Europe/Berlin
      - SA_REGLER=70
      - SA_SERIENNUMMER=xxx
      - SA_WR_IP=192.168.10.119
      - SA_WR_PORT=502
      - SA_OBJECT=Home
      - SA_INFLUX_LOCAL_ENABLED=false
      - SA_INFLUX_REMOTE_ENABLED=true
      - SA_INFLUX_HOST=influxdb
      - SA_INFLUX_USERNAME=admin
      - SA_INFLUX_PASSWORD=solaranzeige

  influxdb:
    image: "docker.io/influxdb"
    restart: "unless-stopped"
    volumes:
      - ./data/influx:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=solaranzeige
      - DOCKER_INFLUXDB_INIT_ORG=solaranzeige
      - DOCKER_INFLUXDB_INIT_BUCKET=solaranzeige

  grafana:
    image: "docker.io/grafana/grafana:main"
    restart: "unless-stopped"
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_INSTALL_PLUGINS=fetzerch-sunandmoon-datasource, briangann-gauge-panel, agenty-flowcharting-panel
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_USER=solaranzeige
      
