version: "2"

services:
  solaranzeige:
    build: .
#    image: "takealug/solaranzeige:latest"
    container_name: Solaranzeige
    restart: "unless-stopped"
    environment:
      - PUID=99
      - PGID=100
      - TIMEZONE=Europe/Berlin
      - UPDATE=no
      - MOSQUITTO=yes
      - INFLUXDB=yes
    volumes:
      - ./app/var/www:/var/www
    tmpfs:
      - /var/log
      - /tmp
    ports:
      - 1883:1883
      - 8080:80

  influxdb:
    image: "docker.io/influxdb"
    restart: "unless-stopped"
    volumes:
      - ./data/influx:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=solaranzeige
      - DOCKER_INFLUXDB_INIT_ORG=solaranzeige
      - DOCKER_INFLUXDB_INIT_BUCKET=solaranzeige

  grafana:
    image: "docker.io/grafana/grafana:main"
    restart: "unless-stopped"
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=fetzerch-sunandmoon-datasource, briangann-gauge-panel, agenty-flowcharting-panel
