version: "2"

services:
  solaranzeige:
    build: .
#    image: "takealug/solaranzeige:latest"
    container_name: Solaranzeige
    restart: "unless-stopped"
    environment:
      - TIMEZONE=Europe/Berlin
      - SA_REGLER=70
      - SA_SERIENNUMMER=A22B10A2499
      - SA_WR_IP=192.168.10.119
      - SA_WR_PORT=502
      - SA_OBJECT=Home
      - SA_INFLUX_LOCAL_ENABLED=false
      - SA_INFLUX_REMOTE_ENABLED=true
      - SA_INFLUX_HOST=influxdb
    volumes:
      - ./app/var/www:/var/www
    tmpfs:
      - /var/log
      - /tmp
    ports:
      - 1883:1883
      - 8080:80

  influxdb:
    image: "docker.io/influxdb"
    restart: "unless-stopped"
    volumes:
      - ./data/influx:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=solaranzeige
      - DOCKER_INFLUXDB_INIT_ORG=solaranzeige
      - DOCKER_INFLUXDB_INIT_BUCKET=solaranzeige

  grafana:
    image: "docker.io/grafana/grafana:main"
    restart: "unless-stopped"
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=fetzerch-sunandmoon-datasource, briangann-gauge-panel, agenty-flowcharting-panel
