#!/bin/bash
echo "##################################"
echo "# Initial Setup for Solaranzeige #"
echo "##################################"
echo ""

echo "create necessary files/directories..."
mkdir -p /var/www/html &>/dev/null
mkdir -p /var/www/html/phpinc &>/dev/null
mkdir -p /var/www/html/css &>/dev/null
mkdir -p /var/www/html/database &>/dev/null
mkdir -p /var/www/html/images &>/dev/null
mkdir -p /var/www/log &>/dev/null
mkdir -p /var/www/pipe &>/dev/null
mkdir -p /solaranzeige &>/dev/null
mkdir -p /solaranzeige/config &>/dev/null
mkdir -p /var/www/log/apache2 &>/dev/null
mkdir -p /pvforecast &>/dev/null
mkdir -p /run/mosquitto &>/dev/null

if [[ ! -f /var/www/log/solaranzeige.log ]]; then
  touch /var/www/log/solaranzeige.log
fi

if [[ ! -f /var/www/log/update.log ]]; then
  touch /var/www/log/update.log
fi

echo ""
echo "downloading Main Program..."

chmod -R 777 /solaranzeige
chmod -R 777 /var/www
chmod -R 777 /var/lib/influxdb
chmod -R 777 /var/lib/grafana
chmod -R 777 /pvforecast
chmod -R 777 /run/mosquitto

su -s /bin/bash -c "TERM=xterm /usr/local/sbin/solaranzeige-update"

echo ""
echo "Installing PVForecast..."
su -s /bin/bash -c "TERM=xterm /usr/local/sbin/pvforecast-update"

chmod +x /solaranzeige/setup
chmod +x /solaranzeige/statusmail
chmod +x /solaranzeige/support

cd /var/www/html && rm -rf /tmp/git

echo ""
echo "##############################################################################################"
echo "# Initial Setup for Solaranzeige completed, please run /solaranzeige/setup for Configuration #"
echo "# example : docker exec -ti Solaranzeige /solaranzeige/setup                                 #"
echo "##############################################################################################"
echo ""

tail -f /var/www/log/solaranzeige.log
