#!/bin/bash
set -e
set -f

USERNAME="root"

if [[ -z "${TIMEZONE}" ]]; then
  TIMEZONE='Europe/Berlin'
fi

if [[ -z "${GROUP_ID}" ]]; then
  GROUP_ID='100'
fi

if [[ -z "${USER_ID}" ]]; then
  USER_ID='99'
fi

if [[ -z "${UPDATE}" ]]; then
  UPDATE='no'
fi

ln -fs /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
dpkg-reconfigure -f noninteractive tzdata

echo "${USERNAME}:x:${USER_ID}:${GROUP_ID}:$USERNAME}:/:/sbin/nologin" >> /etc/passwd
echo "${USERNAME}:!::0:::::" >> /etc/shadow

if ! getent group ${GROUP_ID}; then
  echo "${USERNAME}:x:${GROUP_ID}:" >> /etc/group
fi

chown -R ${USER_ID}:${GROUP_ID} /solaranzeige
chown -R ${USER_ID}:${GROUP_ID} /var/www
chmod -R 777 /solaranzeige
chmod -R 777 /var/www
chmod -R 777 /var/lib/influxdb
chmod -R 777 /var/lib/grafana

if [[ ! -f /var/www/html/user.config.php ]] || [[ ! -f /var/www/html/1.user.config.php ]] || [[ ! -f /var/www/html/2.user.config.php ]] || [[ ! -f /var/www/html/3.user.config.php ]] || [[ ! -f /var/www/html/4.user.config.php ]] || [[ ! -f /var/www/html/5.user.config.php ]] || [[ ! -f /var/www/html/6.user.config.php ]]; then
  /usr/local/sbin/solaranzeige.setup
fi

if [[ "${UPDATE}" = "yes" ]]; then
  /usr/local/sbin/solaranzeige.update
fi

su -s /bin/bash -c "TERM=xterm /usr/local/sbin/solaranzeige.process"
